name: veSAL Arm64 Pipeline
trigger:
  # Run merge request pipeline automatically
  # https://bytedance.feishu.cn/wiki/wikcn0XxotllYX3nzz7AEv1h07d#1gAE9h
  change:
  # https://bytedance.feishu.cn/wiki/wikcnmGR04aP3KhZmqr4qxDMNfb
  manual:

# TODO(sjj): Add aarch64 build image for vesal
jobs:
  aarch64-build-and-run-software:
    name: Build on aarch64 host and run software test
    image: hub.byted.org/compile/byte_buster:47170bb5894e127813e2165abb536798
    runs-on:
      arch: arm64
    working-directory: vesal
    steps:
      - name: Build
        commands:
          - apt update && apt install -y libnuma-dev && bash build.sh --enable_err_sim
      - name: Run tests related to arm change
        commands:
          - build/test/dc_format_test
          - build/test/timestamp_test
          - build/test/object_pool_test
