import re
import sys

def parse_c_functions_universal(content):
    # 清理内容
    content_clean = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL)
    content_clean = re.sub(r'//.*?$', '', content_clean, flags=re.MULTILINE)
    content_clean = re.sub(r'^\s*#.*?$', '', content_clean, flags=re.MULTILINE)
    content_clean = re.sub(r'\s+', ' ', content_clean)
    
    functions = []
    
    # 更简单的模式：匹配函数名和参数，然后提取前面的内容作为返回类型
    pattern = r'''
        ([a-zA-Z_][a-zA-Z0-9_]*)                # 函数名
        \s*                                     # 可选空白
        \(\s*                                   # 开括号
        ([^)]*)                                 # 参数
        \s*\)\s*;                               # 闭括号和分号
    '''
    
    func_regex = re.compile(pattern, re.VERBOSE)
    
    # 使用 finditer 获取匹配位置
    for match in func_regex.finditer(content_clean):
        function_name = match.group(1).strip()
        arguments = match.group(2).strip()
        
        # 提取函数名之前的内容作为返回类型
        func_start = match.start(1)
        # 向前查找直到行首或前一个分号
        declaration_start = max(
            content_clean.rfind(';', 0, func_start) + 1,
            content_clean.rfind('\n', 0, func_start) + 1,
            0
        )
        
        return_type = content_clean[declaration_start:func_start].strip()
        
        # 清理返回类型
        return_type = re.sub(r'^\s*(?:extern|static|inline)\s+', '', return_type)
        return_type = re.sub(r'\s+', ' ', return_type)
        
        # 验证
        if (return_type and function_name and
            not return_type.startswith('#') and
            'typedef' not in return_type.lower() and
            not function_name.lower().endswith(('_t', '_type'))):
            
            functions.append({
                'return_type': return_type,
                'func_name': function_name,
                'args': arguments
            })
    
    return functions

def generate_stubs(input_header, output_cc, lib_name):
    """
    Parses a header file and generates a C++ file for dynamic library loading
    using a macro-based function pointer approach.
    """
    functions = []
    with open(input_header, 'r') as f_in:
        content = f_in.read()
        functions = parse_c_functions_universal(content)
    print(f"Found {len(functions)} functions")

    with open(output_cc, 'w') as f_out:
        f_out.write('// This file is automatically generated. DO NOT EDIT.\n')
        f_out.write(f'// Generated by StubGenerator.py\n\n')
        
        f_out.write('#include "dummy_driver_common.h"\n')
        f_out.write('#include <dlfcn.h>\n')
        f_out.write('#include <iostream>\n')
        f_out.write('extern "C" {\n')
        f_out.write(f'#include "{input_header.split("/")[-1]}"\n\n')
        f_out.write('}\n\n')

        f_out.write('// Implementation of the wrapper functions.\n')
        for f in functions:
            return_type = f["return_type"]
            func_name = f["func_name"]
            args = f["args"]
            args_name = args.split(',')
            args_name = [arg.strip().split(' ')[-1].replace('*', '') for arg in args_name]
            if 'void' in args_name:
                args_name.remove('void')
            args_name = ','.join(args_name)
            
            f_out.write(f'MAKE_WRAPPER_FUNC_COMMON({func_name}, {return_type}, {args}) {{\n')

            f_out.write(f'    return FUNC_PTR({func_name})({args_name});\n')
            
            f_out.write('}\n\n')

        f_out.write('// Main initialization function to load all symbols.\n')
        f_out.write(f'bool Load{lib_name}(void) {{\n')
        f_out.write(f'    void* handle = dlopen("{lib_name}.so", RTLD_LAZY | RTLD_LOCAL);\n')
        f_out.write('    if (!handle) {\n')
        f_out.write('        std::cerr << "Warning: handle of shared lib is null";\n')
        f_out.write('        return false;\n')
        f_out.write('    }\n\n')
        
        for f in functions:
            f_out.write(f'    LOAD_SYM_COMMON(handle, {f["func_name"]});\n')

        f_out.write('    return true;\n')
        f_out.write('teardown:\n')
        f_out.write('    return false;\n')
        f_out.write('}\n')

    print(f'Successfully generated stub file: {output_cc}')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print('Usage: python generate_qat_dyn_stubs.py <input_header.h> <lib_name>')
        sys.exit(1)

    input_header = sys.argv[1]
    lib_name = sys.argv[2]
    output_h = lib_name + '_dummy.h'

    generate_stubs(input_header, output_h, lib_name)