// This file is automatically generated. DO NOT EDIT.
// Generated by StubGenerator.py

#include <dlfcn.h>

#include <iostream>

#include "dummy_driver_common.h"
extern "C" {
#include "kaezip.h"
}

// Implementation of the wrapper functions.
MAKE_WRAPPER_FUNC_COMMON(kaezlib_get_version, int, KAEZlibVersion* ver) {
    return FUNC_PTR(kaezlib_get_version)(ver);
}

MAKE_WRAPPER_FUNC_COMMON(kz_get_devices, int, void) {
    return FUNC_PTR(kz_get_devices)();
}

MAKE_WRAPPER_FUNC_COMMON(kz_deflate, int, z_streamp strm, int flush) {
    return FUNC_PTR(kz_deflate)(strm, flush);
}

MAKE_WRAPPER_FUNC_COMMON(kz_inflate, int, z_streamp strm, int flush) {
    return FUNC_PTR(kz_inflate)(strm, flush);
}

MAKE_WRAPPER_FUNC_COMMON(kz_inflateEnd, int, z_streamp strm) {
    return FUNC_PTR(kz_inflateEnd)(strm);
}

MAKE_WRAPPER_FUNC_COMMON(kz_deflateInit2_,
                         int,
                         z_streamp strm,
                         int level,
                         int metho,
                         int windowBit,
                         int memLevel,
                         int strategy,
                         const char* version,
                         int stream_size) {
    return FUNC_PTR(kz_deflateInit2_)(
        strm, level, metho, windowBit, memLevel, strategy, version, stream_size);
}

MAKE_WRAPPER_FUNC_COMMON(
    kz_inflateInit2_, int, z_streamp strm, int windowBits, const char* version, int stream_size) {
    return FUNC_PTR(kz_inflateInit2_)(strm, windowBits, version, stream_size);
}

MAKE_WRAPPER_FUNC_COMMON(kz_deflateEnd, int, z_streamp strm) {
    return FUNC_PTR(kz_deflateEnd)(strm);
}

MAKE_WRAPPER_FUNC_COMMON(kz_inflateReset, int, z_streamp strm) {
    return FUNC_PTR(kz_inflateReset)(strm);
}

MAKE_WRAPPER_FUNC_COMMON(kz_deflateReset, int, z_streamp strm) {
    return FUNC_PTR(kz_deflateReset)(strm);
}

MAKE_WRAPPER_FUNC_COMMON(kz_getAutoInflateAlgType, int, z_streamp strm) {
    return FUNC_PTR(kz_getAutoInflateAlgType)(strm);
}

MAKE_WRAPPER_FUNC_COMMON(kz_do_inflateInit, int, z_streamp strm, int alg_comp_type) {
    return FUNC_PTR(kz_do_inflateInit)(strm, alg_comp_type);
}

MAKE_WRAPPER_FUNC_COMMON(getInflateStateWrap, int, z_streamp strm) {
    return FUNC_PTR(getInflateStateWrap)(strm);
}

MAKE_WRAPPER_FUNC_COMMON(getInflateKaezipCtx, unsigned long, z_streamp strm) {
    return FUNC_PTR(getInflateKaezipCtx)(strm);
}

MAKE_WRAPPER_FUNC_COMMON(setInflateKaezipCtx, void, z_streamp strm, unsigned long kaezip_ctx) {
    return FUNC_PTR(setInflateKaezipCtx)(strm, kaezip_ctx);
}

MAKE_WRAPPER_FUNC_COMMON(getDeflateKaezipCtx, unsigned long, z_streamp strm) {
    return FUNC_PTR(getDeflateKaezipCtx)(strm);
}

MAKE_WRAPPER_FUNC_COMMON(setDeflateKaezipCtx, void, z_streamp strm, unsigned long kaezip_ctx) {
    return FUNC_PTR(setDeflateKaezipCtx)(strm, kaezip_ctx);
}

MAKE_WRAPPER_FUNC_COMMON(KAEZIP_compress_async_in_session,
                         int,
                         void* sess,
                         const struct kaezip_buffer_list* src,
                         struct kaezip_buffer_list* dst,
                         kaezip_async_callback callback,
                         struct kaezip_result* result) {
    return FUNC_PTR(KAEZIP_compress_async_in_session)(sess, src, dst, callback, result);
}

MAKE_WRAPPER_FUNC_COMMON(KAEZIP_async_polling_in_session, void, void* sess, int budget) {
    return FUNC_PTR(KAEZIP_async_polling_in_session)(sess, budget);
}

MAKE_WRAPPER_FUNC_COMMON(KAEZIP_create_async_compress_session,
                         void*,
                         iova_map_fn usr_map,
                         const device_config_t* config) {
    return FUNC_PTR(KAEZIP_create_async_compress_session)(usr_map, config);
}

MAKE_WRAPPER_FUNC_COMMON(KAEZIP_destroy_async_compress_session, void, void* sess) {
    return FUNC_PTR(KAEZIP_destroy_async_compress_session)(sess);
}

MAKE_WRAPPER_FUNC_COMMON(KAEZIP_create_async_decompress_session,
                         void*,
                         iova_map_fn usr_map,
                         const device_config_t* config) {
    return FUNC_PTR(KAEZIP_create_async_decompress_session)(usr_map, config);
}

MAKE_WRAPPER_FUNC_COMMON(KAEZIP_destroy_async_decompress_session, void, void* sess) {
    return FUNC_PTR(KAEZIP_destroy_async_decompress_session)(sess);
}

MAKE_WRAPPER_FUNC_COMMON(KAEZIP_decompress_async_in_session,
                         int,
                         void* sess,
                         const struct kaezip_buffer_list* src,
                         struct kaezip_buffer_list* dst,
                         kaezip_async_callback callback,
                         struct kaezip_result* result) {
    return FUNC_PTR(KAEZIP_decompress_async_in_session)(sess, src, dst, callback, result);
}

MAKE_WRAPPER_FUNC_COMMON(KAEZIP_reset_session, void, void* sess) {
    return FUNC_PTR(KAEZIP_reset_session)(sess);
}

MAKE_WRAPPER_FUNC_COMMON(KAEZIP_create_async_compress_session_zlib,
                         void*,
                         iova_map_fn usr_map,
                         int level,
                         int windowBits) {
    return FUNC_PTR(KAEZIP_create_async_compress_session_zlib)(usr_map, level, windowBits);
}

MAKE_WRAPPER_FUNC_COMMON(KAEZIP_create_async_decompress_session_zlib, void*, iova_map_fn usr_map) {
    return FUNC_PTR(KAEZIP_create_async_decompress_session_zlib)(usr_map);
}

MAKE_WRAPPER_FUNC_COMMON(KAEZIP_get_devices, const struct zip_dev*, unsigned int* num) {
    return FUNC_PTR(KAEZIP_get_devices)(num);
}

// Main initialization function to load all symbols.
bool Loadlibkaezip(void) {
    void* handle = dlopen("libkaezip.so", RTLD_LAZY | RTLD_LOCAL);
    if (!handle) {
        std::cerr << "Warning: handle of shared lib is null";
        return false;
    }

    LOAD_SYM_COMMON(handle, kaezlib_get_version);
    LOAD_SYM_COMMON(handle, kz_get_devices);
    LOAD_SYM_COMMON(handle, kz_deflate);
    LOAD_SYM_COMMON(handle, kz_inflate);
    LOAD_SYM_COMMON(handle, kz_inflateEnd);
    LOAD_SYM_COMMON(handle, kz_deflateInit2_);
    LOAD_SYM_COMMON(handle, kz_inflateInit2_);
    LOAD_SYM_COMMON(handle, kz_deflateEnd);
    LOAD_SYM_COMMON(handle, kz_inflateReset);
    LOAD_SYM_COMMON(handle, kz_deflateReset);
    LOAD_SYM_COMMON(handle, kz_getAutoInflateAlgType);
    LOAD_SYM_COMMON(handle, kz_do_inflateInit);
    LOAD_SYM_COMMON(handle, getInflateStateWrap);
    LOAD_SYM_COMMON(handle, getInflateKaezipCtx);
    LOAD_SYM_COMMON(handle, setInflateKaezipCtx);
    LOAD_SYM_COMMON(handle, getDeflateKaezipCtx);
    LOAD_SYM_COMMON(handle, setDeflateKaezipCtx);
    LOAD_SYM_COMMON(handle, KAEZIP_compress_async_in_session);
    LOAD_SYM_COMMON(handle, KAEZIP_async_polling_in_session);
    LOAD_SYM_COMMON(handle, KAEZIP_create_async_compress_session);
    LOAD_SYM_COMMON(handle, KAEZIP_destroy_async_compress_session);
    LOAD_SYM_COMMON(handle, KAEZIP_create_async_decompress_session);
    LOAD_SYM_COMMON(handle, KAEZIP_destroy_async_decompress_session);
    LOAD_SYM_COMMON(handle, KAEZIP_decompress_async_in_session);
    LOAD_SYM_COMMON(handle, KAEZIP_reset_session);
    LOAD_SYM_COMMON(handle, KAEZIP_create_async_compress_session_zlib);
    LOAD_SYM_COMMON(handle, KAEZIP_create_async_decompress_session_zlib);
    LOAD_SYM_COMMON(handle, KAEZIP_get_devices);
    return true;
teardown:
    return false;
}
